AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sarahs Thought Pad - Complete Serverless Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: sarahs-thought-pad

Resources:
  ThoughtsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Thoughts-CFN-Version
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                Resource: !GetAtt ThoughtsTable.Arn

  SaveThoughtFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: save-thought-function-cfn
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub "${GitCommit}/lambda.zip"
        
  ThoughtsApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: thoughts-api-cfn
      Description: API for Sarahs Thought Pad

  ThoughtsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ThoughtsApi
      ParentId: !GetAtt ThoughtsApi.RootResourceId
      PathPart: thoughts

  PostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ThoughtsApi
      ResourceId: !Ref ThoughtsResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SaveThoughtFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SaveThoughtFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ThoughtsApi}/*/POST/thoughts"

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ThoughtsApi
    DependsOn: PostMethod

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref ThoughtsApi
      DeploymentId: !Ref ApiDeployment
